program            : statement_list

statement_list     : statements

statements         : simple_stmt SEMICOLON
                   | compound_stmt

simple_stmt        : varDecl_stmt
                   | pass_stmt
                   | print_stmt
                   | return_stmt
                   | break_stmt
                   | continue_stmt
                   | import_stmt
                   | raise_stmt
                   | import_stmt

varDecl_stmt       : LET variable (COMMA variable)* (ASSIGN expr (COMMA expr)*)?
                   | CONST variable (COMMA variable)* ASSIGN expr (COMMA expr)*


return_stmt        : RETURN expr

compound_stmt      : if_stmt
                   | for_stmt
                   | while_stmt
                   | try_stmt
                   | funcdef
                   | classdef

variable           : ID


expr               : comp-expr (OR comp-expr)*

and-expr           : comp-expr (AND comp-expr)*

comp-expr          : arith-expr (binary_operation arith-expr)*

arith-expr         : term ((PLUS|MINUS|OR) term)*

term               : factor ((MUL|DIV|AND) factor)*

factor             :(PLUS|MINUS) INT
                   |(PLUS|MINUS) FLOAT
                   |SCINUM
                   |HEXNUM
                   |OCTNUM
                   |BINNUM
                   | "(" expr ")"
                   |ID

binary_operation   :LT
                   |GT
                   |EQ
                   |NEQ
                   |LTE
                   |GTE 
